#ifndef SOCKS5_H
#define SOCKS5_H

/* SOCKS5 protocol constants (RFC1928) */
#define SOCKS_VERSION 0x05

/* Authentication methods */
#define SOCKS_HELLO_NOAUTHENTICATION_REQUIRED 0x00
#define SOCKS_HELLO_USERNAME_PASSWORD 0x02
#define SOCKS_HELLO_NO_ACCEPTABLE_METHODS 0xFF

/* Commands */
#define SOCKS_CMD_CONNECT 0x01
#define SOCKS_CMD_BIND 0x02
#define SOCKS_CMD_UDP_ASSOCIATE 0x03

/* Address types */
#define SOCKS_ATYP_IPV4 0x01
#define SOCKS_ATYP_FQDN 0x03
#define SOCKS_ATYP_IPV6 0x04

/* Reply codes */
#define SOCKS_REPLY_SUCCEEDED 0x00
#define SOCKS_REPLY_GENERAL_FAILURE 0x01
#define SOCKS_REPLY_NOT_ALLOWED 0x02
#define SOCKS_REPLY_NET_UNREACHABLE 0x03
#define SOCKS_REPLY_HOST_UNREACHABLE 0x04
#define SOCKS_REPLY_CONN_REFUSED 0x05
#define SOCKS_REPLY_TTL_EXPIRED 0x06
#define SOCKS_REPLY_CMD_NOT_SUPPORTED 0x07
#define SOCKS_REPLY_ATYP_NOT_SUPPORTED 0x08

#endif
